version: '3.8'

services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
      - POSTGRES_DB=testdb

  spring-app:
    build:
      dockerfile: Dockerfile
    image: spring-app
    container_name: spring-app
    ports:
     - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  spring-app_network:
    driver: bridge