version: '3.8'

services:

   database:
      image: postgres:14.1-alpine
      container_name: database-container
      ports:
      - 5432:5432
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
      - POSTGRES_DB=testdb
      volumes:
      - ./localdb/:/docker-entrypoint-initdb.d

   spring-app:
      build:
         dockerfile: Dockerfile
      image: spring-app
      container_name: spring-app
      environment:
         - spring.r2dbc.url=r2dbc:postgresql://host.docker.internal:5432/testdb
      ports:
      - "8080:8080"
      depends_on:
      - database
      links:
      - database
      networks:
      - spring-app_network
      extra_hosts:
      - host.docker.internal:host-gateway

networks:
   spring-app_network:
      driver: bridge